### ISSUE TITLE
Feature request for backend: complete / uncomplete toggle

### ISSUE THREAD

**Issue by dpaschal-lf** [Learning-Fuze/c4_TDL#106]
@scbowler 
- Add completed to todo database.  
   - boolean: whether or not the todo item is complete
- Add complete toggle function to todo api
   - Input:
     - complete: boolean - value to change complete field to
     - id: number - id of the todo item to change
   -  output: 
      - success: boolean - operation succeeded
      - errors: array - array of error strings

**Comment by scbowler** [comment]
On it

**Comment by scbowler** [comment]
added `validateUserInfo` takes same data as `newAccount` but only validates the data and does not affect the DB. Also added complete column to DB, 0=incomplete 1=complete. `updateCompleteStatus` requires `$_POST['complete']` as int, 0 or 1 and `$_POST['postId']` as int

**Comment by scbowler** [comment]
@dpaschal-lf

**Comment by scbowler** [comment]
done
