### ISSUE TITLE
HTML Login-Form

### ISSUE THREAD

**Issue by Jamus123** [Learning-Fuze/c4_TDL#12]
-Use Bootstrap modal http://www.w3schools.com/bootstrap/bootstrap_modal.asp
- Use bootstrap horizontal form http://www.w3schools.com/bootstrap/bootstrap_forms.asp
- Bootstrap button(Only keep the submit button aka remove the footer)
-Make sure the user can't click off the screen in order to close the login(aka force the user to input their info)

**Comment by kcorros** [comment]
finished specs
