### ISSUE TITLE
T1 - posting todo item doesn't work

### ISSUE THREAD

**Issue by dpaschal-lf** [Learning-Fuze/c4_TDL#152]
Adding an item to todo list doesn't work nor give any sort of feedback:

![screen shot 2015-06-04 at 1 09 38 pm](https://cloud.githubusercontent.com/assets/10343746/7993471/2d16cebe-0abb-11e5-99ec-301ab01f780b.png)

**Comment by mkidushim** [comment]
This is caused because of the way that we are sending date and time input values.  We are fixing this bug now.

**Comment by mkidushim** [comment]
Fixed this should add now was not working becuase of the date and time input
