### ISSUE TITLE
T2 - logging in does not initially show todo items

### ISSUE THREAD

**Issue by dpaschal-lf** [Learning-Fuze/c4_TDL#156]
![screen shot 2015-06-04 at 1 31 33 pm](https://cloud.githubusercontent.com/assets/10343746/7993875/18bad2c8-0abe-11e5-86e8-613674af8d53.png)

**Comment by LandedE** [comment]
Fixed this issue opened pull request  referencing this issue.

**Comment by Jamus123** [comment]
fixed
