### ISSUE TITLE
UPDATED AS OF 1.7 todo create

### ISSUE THREAD

**Issue by mkidushim** [Learning-Fuze/c4_TDL#161]
request URL: http://s-apis.learningfuze.com/todo/get
input (POST):
userId: number - User's ID to fetch todo items for
output (JSON):
data: array of objects
id: int - todo item ID
userId: int - todo item's owner
title: string - title of the todo item
timeStamp: int - unix timestamp of the duedate
details: string - details of the todo item
NEW AS OF 1.7 completed: boolean - whether the item has been flagged as completed or not
success: boolean - success or failure of the operation
errors: array - array of error messages, if any

**Comment by dnguy** [comment]
only checking for this new completed: boolean 

NEW AS OF 1.7 completed: boolean - whether the item has been flagged as completed or not

**Comment by mkidushim** [comment]
Add ability to set individual items to complete or incomplete
request URL: http://s-apis.learningfuze.com/todo/updateCompleteStatus
input (POST):
postId: number - id of the post to change
complete: number - status of the post. 1 for complete, 0 for incomplete
output (JSON):
success: boolean - true or false user information is valid
errors: array - array of error messages, if any
msgs: status message if successful
