### ISSUE TITLE
T1 Beta review requirements

### ISSUE THREAD

**Issue by dpaschal-lf** [Learning-Fuze/c4_TDL#169]
- Screenshots of new functionality
    - update functionality
    - complete / incomplete functionality
    - refreshed page while user is logged in : return to at least logged in user home
- Link to Beta demo code for testing
- Pull Request for Beta
- Any special instructions for running code 
- Notes about what isn't fully functional for Beta

**Comment by dpaschal-lf** [comment]
TIME

**Comment by mkidushim** [comment]
update functionality
![](https://s3.amazonaws.com/uploads.hipchat.com/165467/1990075/RXZnUbhQwdyYGyu/Screen%20Shot%202015-06-04%20at%205.51.31%20PM.png)
validation
![screen shot 2015-06-04 at 6 07 14 pm](https://cloud.githubusercontent.com/assets/10224479/7997603/ae45e708-0ae4-11e5-97bc-73ba97c1c8ff.png)
complete/incomplete functionality
![](https://s3.amazonaws.com/uploads.hipchat.com/165467/1990075/7ifZEXsIy2gG2m8/Screen%20Shot%202015-06-04%20at%205.51.52%20PM.png)

**Comment by dpaschal-lf** [comment]
- update functionality **complete**
- complete / incomplete functionality **complete**
- refreshed page while user is logged in : return to at least logged in user home **####incomplete**
- Link to Beta demo code for testing **####incomplete**
- Pull Request for Beta **complete**
- Notes about what isn't fully functional for Beta **incomplete**

**Comment by mkidushim** [comment]
192.168.1.178/lf_projects/MySandbox%20/c4_TDL/

**Comment by mkidushim** [comment]
Update inside user login page press pull to do list
![screen shot 2015-06-04 at 10 21 34 pm](https://cloud.githubusercontent.com/assets/10224479/7999901/1d9596bc-0b08-11e5-8e6e-19a20217b0e8.png)
