### ISSUE TITLE
T2 - Beta review requirements:

### ISSUE THREAD

**Issue by dpaschal-lf** [Learning-Fuze/c4_TDL#170]
- Screenshots of new functionality
    - update functionality
    - complete / incomplete functionality
    - refreshed page while user is logged in : return to at least logged in user home
- Link to Beta demo code for testing
- Pull Request for Beta
- Any special instructions for running code 
- Notes about what isn't fully functional for Beta

**Comment by Jamus123** [comment]
Complete functionality(does not append anywhere currently)
![compelted](https://cloud.githubusercontent.com/assets/8881131/7997388/16cf13c0-0ae1-11e5-87f7-a88ffaf24182.PNG)

**Comment by Jamus123** [comment]
http://192.168.1.229/lf_projects/Sandbox/c4_TDL/

--Update function not available
--Refreshed page fcuntionality not available
-Complete/Incomplete works but has no way to view

**Comment by dpaschal-lf** [comment]
TIME

**Comment by dpaschal-lf** [comment]
- update functionality **####notice**
- complete / incomplete functionality **####notice**
- refreshed page while user is logged in : return to at least logged in user home **####notice**
- Link to Beta demo code for testing  **complete**
- Pull Request for Beta  **complete**
- Notes about what isn't fully functional for Beta **complete**
