### ISSUE TITLE
Team#1 - AJAX request to server to log in

### ISSUE THREAD

**Issue by mkidushim** [Learning-Fuze/c4_TDL#18]
request URL: http://s-apis.learningfuze.com/todo/login
input (POST):
   username
   password
output:
   success: true/false - whether or not the login was successful
   status: number - the status of the account (1 is normal user)
   email: string - the user's email
  lastName: string - the user's last name
   firstName: string - the user's first name
   id: number - the user's ID number
    errors: array - an array of strings, each holding an error that occurred during the login

**Comment by dnguy** [comment]
completed ajax request to server login
