### ISSUE TITLE
Issue with validating from server http://s-apis.learningfuze.com/todo/validateUserInfo

### ISSUE THREAD

**Issue by mkidushim** [Learning-Fuze/c4_TDL#238]
Im not sure if this is doing the right thing before it was checking for password1 and password2 now it only needs username, firstname, lastname and email.  Below is a screen shot of the postman i used to check it after finding the initial probem in my code.  
![screen shot 2015-06-06 at 9 46 37 am](https://cloud.githubusercontent.com/assets/10224479/8020532/43cedac6-0c31-11e5-95a9-f4daa21258bc.png)

**Comment by dpaschal-lf** [comment]
@scbowler Scott, can you check on this?

**Comment by scbowler** [comment]
@dpaschal-lf Update pushed to gitHub, problem should be fixed
