### ISSUE TITLE
Team#1 - tie in "list all todo items" frontend to backend

### ISSUE THREAD

**Issue by mkidushim** [Learning-Fuze/c4_TDL#82]
request URL: http://s-apis.learningfuze.com/todo/get
input (POST):
    userId: number - User's ID to fetch todo items for
output (JSON):
   data: array of objects
   id: int - todo item ID
  userID: int - todo item's owner
  title: string - title of the todo item
  timeStamp: int - unix timestamp of the due date
   details: string - details of the todo item
   success: boolean - success or failure of the operation
    errors: array - array of error messages, if any

**Comment by ParrisSikorski** [comment]
completed the ajax call it now brings up 1 todo list item that is tied to that specific id

**Comment by ParrisSikorski** [comment]
most of the functionality was already there just had to replace the url to the server
