### ISSUE TITLE
todo/create

### ISSUE THREAD

**Issue by LandedE** [Learning-Fuze/c4_TDL#84]
I am attempting to use postman to test the functionality of this api but am getting an error. It seems that the data I am sending should be acceptable. 
![screen shot 2015-06-03 at 4 47 33 pm](https://cloud.githubusercontent.com/assets/11826315/7973952/c6a4d0cc-0a10-11e5-8a73-c0fcf92448b2.png)

**Comment by Jamus123** [comment]
Sending up to senior developer

**Comment by dpaschal-lf** [comment]
@Jamus123 @LandedE Try taking the quote marks out of the inputs.
Also test the date given in phpfiddle to see if strtotime('your date') works or not.
@scbowler Is the server sanitizing the quote marks on incoming data?
