### ISSUE TITLE
bug with logout function

### ISSUE THREAD

**Issue by dnguy** [Learning-Fuze/c4_TDL#98]
I'm no longer able to logout. It looks like it's trying to match my user session with janet's and it's returning an error
![screen shot 2015-06-03 at 11 39 33 pm](https://cloud.githubusercontent.com/assets/11825055/7978413/e48cccf0-0a49-11e5-9feb-40cb2fa8a3f4.png)

**Comment by mkidushim** [comment]
Works good !!!
